pipeline{
    
    environment {
        APP_VERSION = "1.0"
    }
    
    stages{
        stage("stage 1"){
            steps{
                sh 'env'
            }
            
        }
    }
}   