pipeline{
    agent{
        label "CI"
    }
    environment {
        APP_VERSION = "1.0"
    }
    
    stages{
        stage("stage 1"){
            environment{
                APP_VERSION = "2.0"
            }
            steps{
                sh 'env'
            }
            
        }
    }
}   